### ISSUE TITLE
Introduce CeleryConnectionException

### ISSUE THREAD

**Issue by ergonlogic** [gjedeer/celery-php#106]
If incorrect credentials are used, we receive:

> The website encountered an unexpected error. Please try again later.
> 
> PhpAmqpLib\Exception\AMQPProtocolConnectionException: ACCESS_REFUSED - Login was refused using authentication mechanism AMQPLAIN. For details see the broker logfile. in PhpAmqpLib\Connection\AbstractConnection->connection_close() (line 661 of vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php).
> 
> call_user_func(Array, Object) (Line: 199)
> PhpAmqpLib\Channel\AbstractChannel->dispatch('10,50', '', NULL) (Line: 341)
> PhpAmqpLib\Channel\AbstractChannel->wait(Array) (Line: 212)
> PhpAmqpLib\Connection\AbstractConnection->connect() (Line: 180)
> PhpAmqpLib\Connection\AbstractConnection->__construct('incorrect', 'guest', '/', , 'AMQPLAIN', NULL, 'en_US', Object, 0) (Line: 50)
> PhpAmqpLib\Connection\AMQPStreamConnection->__construct('localhost', 5672, 'incorrect', 'guest', '/') (Line: 78)
> AMQPLibConnector->GetConnectionObject(Array) (Line: 188)
> CeleryAbstract::InitializeAMQPConnection(Array) (Line: 170)
> CeleryAbstract->BuildConnection(Array) (Line: 125)
> CeleryAdvanced->__construct(Array, Array) (Line: 195)
> [...]

To catch this exception, we need to do something like:

```
    use CeleryAdvanced;
    use PhpAmqpLib\Exception\AMQPProtocolConnectionException;

    [...]

    try {
            $queue = new CeleryAdvanced($broker, $backend);
            return $queue;
    }
    catch(AMQPProtocolConnectionException $e) {
            [...]
    }
```

It'd be more convenient to add a new exception (CeleryConnectionException), as we then wouldn't need to concerns ourselves with the underlying library.

**Comment by gjedeer** [comment]
Makes sense, PR welcome.

**Comment by ergonlogic** [comment]
See #107
