### ISSUE TITLE
Throttled producers stall indefinately

### ISSUE THREAD

**Issue by chisleu** [gjedeer/celery-php#31]
If RabbitMQ throttles the producers for any reason (low disk / memory) an infinite loop is encountered by celery-php or an underlying library. I would expect it to fail after a timeout.

**Comment by jdufresne** [comment]
@chisleu Are you still experiencing this? Have you tried the latest versions or master branch along with the latest version of php-amqplib? Do you have a minimal test script that I can use to reproduce the issue?

**Comment by TWC-JosephNicholasYarbrough** [comment]
@chisleu here:
I left the company that used PHP and no longer have their work products unfortunately.

We ended up using a simple micro-service to relay messages to celery over HTTP

**Comment by jdufresne** [comment]
Thanks for the response. As I can't reproduce the issue, closing.
