### ISSUE TITLE
[DX] Add version information for composer.

### ISSUE THREAD

**Issue by gena01** [gjedeer/celery-php#34]
composer show massivescale/celery-php shows this:
name     : massivescale/celery-php
descrip. : PHP client for Celery task queue
keywords : AMQP, celery, cron, python, queue, task
versions : dev-master,  dev-peclonly, dev-php-amqplib, dev-celery31, dev-redis
type     : library
license  : BSD-2-Clause
source   : [git] https://github.com/gjedeer/celery-php.git 0132462faeb22b7900b742da3f8af34ccffd6235
dist     : [zip] https://api.github.com/repos/gjedeer/celery-php/zipball/0132462faeb22b7900b742da3f8af34ccffd6235 0132462faeb22b7900b742da3f8af34ccffd6235
names    : massivescale/celery-php

autoload
classmap
celery.php

requires
ext-amqp >=1.0.0
1. There are no versions here only dev branches.
2. Would you be open to fixing composer.json and branches as a start to at least try and expose some version information. From the looks of it master is "2.0-dev" and peclonly is "1.0-dev".?
3. composer.json should NOT hard-code version information.
4. You should be using branch aliases for dev branches to map version information. I could create Pull Request(s) to fix this if you are willing to merge them.
5. Would be nice to cut some sort of tag(s)/release(s) to let users use stable version of the library and to be able to track changes between versions somehow without relying on "dev-master" or master branch. (which has potential to break things, also harder to pin things to specific version(s)).

**Comment by jdufresne** [comment]
I believe this has been fixed. The recent releases have been done using git tags, which packagist picks up automatically. @gena01 can you confirm the problem has been fixed for you? If so, I think we can safely close this issue.

I think the really old branches could probably be removed if there is no intention of merging them. If they're removed, they won't appear as version for composer. @gjedeer, what do you think? If you agree I can go ahead and do this for you.

* `php_amqp-0.3`
* `celery31`
* `peclonly`
* `redis`
* `php-amqplib`
* `pull-39-test`

**Comment by gjedeer** [comment]
All apart from php_amqp-0.3 can go. I have some old systems which make use of this branch. Here's a diff to the readme explaining why it's kept: https://github.com/gjedeer/celery-php/commit/5c0560d6865774686ab145a962babaced33395dd

**Comment by jdufresne** [comment]
Done.

@gena01 Please let me know if you continue to experience this issue. Closing until further comment.
