### ISSUE TITLE
require_once('vendor/autoload.php');

### ISSUE THREAD

**Issue by jortsc** [gjedeer/celery-php#38]
Hi gjedeer,

Many thanks for this library. I'm using your library in a php project through composer. But I'm getting an error when it tries to run this code line:
File: amqplibconnectorssl.php
Line: 4
Sentence: require_once('vendor/autoload.php');

Once the lib is installed through composer the structure is:

![screenshot from 2014-10-28 09 22 39](https://cloud.githubusercontent.com/assets/2716468/4805338/acdb9428-5e7b-11e4-8820-f8ddc001cf3e.png)

Obviously, when I deploy my application composer installs or updates my dependencies and it generates the autoload.php, that I use along the whole application. I guess that this require tries to find its own autoload. But, when it is a package for Composer this does not work in this way.
I set the path to my generated vendor/autoload.php file for your require_once('vendor/autoload.php') and all works fine. But it is a workaround and I need a final solution in order to leave the application running in production.

I'm look forward to hear from you.
Many thanks.
Kind regards.

**Comment by jjbubudi** [comment]
I am also having this issue, check my PR https://github.com/gjedeer/celery-php/pull/46

**Comment by alexbain** [comment]
I'm also experiencing this issue.

**Comment by josericardo** [comment]
+1

**Comment by darrencrossley** [comment]
+1 also having this problem - please merge PR.

**Comment by gjedeer** [comment]
Hey,

Fixed. Sorry it took so long.

**Comment by darrencrossley** [comment]
Thanks! :+1:
