### ISSUE TITLE
Not able to figure out how to post a delayed task.

### ISSUE THREAD

**Issue by lankesh** [gjedeer/celery-php#44]
Hi,

I am sure I am missing something here.
I just want to post a task which should be executed after some countdown.
Is there any way I can post such a task from celery-php?

**Comment by rocksfrow** [comment]
@lankesh @gjedeer is there any update on this? has it been merged? that merge link doesn't show me anything.

if it's been merged -- how do I use it? thanks!

**Comment by rocksfrow** [comment]
Ah, I think I found my answer in case anybody else comes across this.

https://github.com/gjedeer/celery-php/blob/ea26823db9fb70babbcdfb3f03d39a73c5a368e9/celery.php#L227-L229
