### ISSUE TITLE
Getting Results

### ISSUE THREAD

**Issue by geoffjukes** [gjedeer/celery-php#45]
I apologize if this is a stupid question - I'm only just realizing that I don't need a result_backend in Celery if I monitor the worker events.

So with celery-php - is a results_backend required? I do not need to persistently store the result of a task, nor do I need to query it more than once. Can I get the results from the task event?

I'd like to replace a webservice call with a Celery worker, but am having a terrible time wrapping my head around how I can communicate the results back *without* a results_backend.

We have RabbitMQ all set up, and are using it for a small number of workers.

Many thanks for any help,

Geoff

**Comment by gjedeer** [comment]
Simplest working config: https://github.com/gjedeer/celery-php/blob/master/testscenario/celeryconfig.py

results_backend is AFAIR only required when you want to use 2 different queues: one for tasks and other for results.

Just check testscenario directory if you're unsure about how to make the Python part work and unittest directory for the PHP part.
