### ISSUE TITLE
Support for Canvas?

### ISSUE THREAD

**Issue by mikesun** [gjedeer/celery-php#47]
AFAICS, there isn't support for Celery Canvas primitives like `signatures`, `group`, `chain`, `chord`, etc. Is that correct?

Has Canvas support been considered or possibly attempted? It's a critical need we have and I'd be up to attempt developing the feature if it makes sense in this client.

Thoughts?

**Comment by gjedeer** [comment]
No, there is no support for that - there was no need for this.

You're welcome to submit a pull request with implementation, tests and documentation or sponsor development.

In case you go with pull request, please don't break current API, any patches breaking current tests will be rejected.

**Comment by gjedeer** [comment]
Feel free to reopen when you have a working implementation
