### ISSUE TITLE
Publisher confirms

### ISSUE THREAD

**Issue by tslater** [gjedeer/celery-php#53]
Is there any way to do publisher confirms with celery-php? I need to make sure that my messages are safe.  

Seems like there is a way to use php-amqplib, which has publisher confirms:
https://github.com/gjedeer/celery-php/commit/712444f57449fb32076335f22e414ce62d41501d

but it hasn't been merged in yet. How are people handling message durability and making sure things aren't dropped??

**Comment by gjedeer** [comment]
It should be easy to implement:

**Comment by gjedeer** [comment]
It should be easy to add an option like this to celery-php:

https://github.com/videlalvaro/php-amqplib/blob/d2b8a292f709b79b1615bef87b1b89bde4c7c347/demo/amqp_publisher_with_confirms.php

I'm not sure why you referred to this patch (which has been merged over a year ago), why do you think it's related?

**Comment by tslater** [comment]
I guess I was confused because the php-amqplib branch says that it's one commit ahead of master? I'm not super familiar with the github interface yet.

**Comment by gjedeer** [comment]
Huh, good catch, I accidentially merged it to a branch. But anyway, this commit is unrelated to what you're asking, or so I think.

**Comment by tslater** [comment]
From what I understood, that commit was a way to use  php-amqplib instead of the compiled amqp extension. Is that right?

Php-amqplib allows for publish confirm, I wasn't sure whether or not the native one did.

**Comment by gjedeer** [comment]
No, php-amqplib support is in master: 

https://github.com/gjedeer/celery-php/blob/master/amqplibconnector.php
https://github.com/gjedeer/celery-php/blob/master/amqplibconnectorssl.php
https://github.com/gjedeer/celery-php/blob/master/amqp.php#L47

**Comment by gjedeer** [comment]
Are you working on a patch to support this or can I close this issue?
