### ISSUE TITLE
library how to use question

### ISSUE THREAD

**Issue by BardiaAfshin** [gjedeer/celery-php#56]
so in the testscenerio folder, your'e defining a task, in the traditional way the celeryproject.org docs define it.

The question is this, how is PHP interacting with this new defined task written in Python?

**Comment by gjedeer** [comment]
https://github.com/gjedeer/celery-php/blob/master/test.php
or
https://github.com/gjedeer/celery-php/blob/master/unittest/CeleryAMQPLibTest.php
https://github.com/gjedeer/celery-php/blob/master/unittest/unittest.php
