### ISSUE TITLE
PECL backend broken; leaves open connections

### ISSUE THREAD

**Issue by jdufresne** [gjedeer/celery-php#57]
I recently upgraded celery-php to version 2.1, posting a large number of tasks no longer work very well.

When posting multiple tasks in a loop like:

```
for ($i = 0; $i < 1000; $i++) {
    $c = new Celery('localhost', 'myuser', 'mypass', 'myvhost');
    $c->PostTask('tasks.add', array(2,2), false);
}
```

Connections are left open and eventually PECL AMQPConnection deadlocks waiting for a connection to RabbitMQ.

Before 2.1 celery-php would close the connection after `PostTask`.

I was never able to use the same `Celery` instance to post multiple tasks.

---

Starting with commit: <https://github.com/gjedeer/celery-php/commit/029c3123f4a923f278c9d1e72438b184e0a2785d>

`celery-php` leaves 1 connection open with the following test case:

```
<?php

require 'celery-php/celery.php';

$c = new Celery('localhost', 'myuser', 'mypass', 'myvhost');
$c->PostTask('tasks.add', array(2,2), false);
while (true) {
}
```

This is because a connection is created inside `Celery::__construct()` that never gets closed. The connection used to be closed inside `PECLAMQPConnector::PostToExchange()`, however now a new connection is built for this function.

Further, after upgrading to master (v2.1) **2 connections** are opened that are never closed. One for the broker and one for the backend.

---

I would like to fix this, but need some clarification. What is the intention?

Is the intention that connections are created eagerly on instantiation? If so, what is the purpose of `CeleryAbstract::$isConnected`?

Is the intention that connections are created lazily in `PostTask()`? If so, why are multiple connections created in `Celery::__construct()`?

Is the intention that a single instantiation of the `Celery` object can call `PostTask` multiple times? If so, perhaps it shouldn't disconnect inside `PECLAMQPConnector::PostToExchange()`.

I'd be happy to submit a pull request to fix these open connections if the above can be explained.

**Comment by jdufresne** [comment]
Ping?

I'm very willing to fix this I just need to know what the intention of the implementation is. Thanks.

**Comment by gjedeer** [comment]
Hi, i don't have access to a computer for the next few days so it's a bit hard to assist you until then.

I remember some pull request changing the code you're referring to, so 'git blame' should refer you to the right one. Anyway, i'll help you when I'm back online.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jdufresne** [comment]
Hi @gjedeer 

Have you had a chance to consider my questions above? I'm willing to put in the work to fix this bug. I'm just trying to avoid wasting time by following the intended design and avoid introducing new bugs.

**Comment by gjedeer** [comment]
Why would you like to create a new Celery instance for every task? The intended usage is: create 1 Celery class instance and call PostTask multiple times.

This way, tasks are posted much faster because connection is reused - and not established when posting each task.

Do you have a good use case where you need to create a Celery instance every time?

**Comment by jdufresne** [comment]
Any chance you could release a new version with this fix? At the moment, I'm stuck pulling from the git repository, but I'd prefer to use a stable release through composer. Thanks.
