### ISSUE TITLE
Default vhost for RabbitMQ

### ISSUE THREAD

**Issue by carlb-jomedia** [gjedeer/celery-php#60]
I think since the recently, the param vhost for Rabbitmq needs to be "/" if you're using the guest user. I just had this problem where I couldn't connect to rabbitmq, and I was getting this error:

{amqp_error,access_refused,
                             "access to vhost '' refused for user 'guest'",
                             'connection.open'}}

because I wasn't passing a vhost that was authorize to the guest user. Maybe I'm wrong, but I just wanted to share this since I lost an hour on this. Maybe it could be added to this readme.

**Comment by gjedeer** [comment]
Tanks
