### ISSUE TITLE
Can't authenticate with Rabbitmq

### ISSUE THREAD

**Issue by carl-boisvert** [gjedeer/celery-php#72]
No matter which version of the library I use, it always give me this:

=PROGRESS REPORT==== 1-Apr-2016::15:54:18 ===
          supervisor: {<0.30364.13>,rabbit_channel_sup}
             started: [{pid,<0.30367.13>},
                       {name,channel},
                       {mfargs,
                           {rabbit_channel,start_link,
                               [1,<0.30356.13>,<0.30365.13>,<0.30356.13>,
                                <<"127.0.0.1:63584 -> 127.0.0.1:5672">>,
                                rabbit_framing_amqp_0_9_1,
                                {user,<<"harvester">>,
                                    [administrator],
                                    [{rabbit_auth_backend_internal,none}]},
                                <<"harvester">>,
                                [{<<"authentication_failure_close">>,bool,
                                  true}],
                                <0.30357.13>,<0.30366.13>]}},
                       {restart_type,intrinsic},
                       {shutdown,70000},
                       {child_type,worker}]

And I can log into the management plugin by the browser, and also, I can do it using the rabbitmq library directly.

I use the basic example:

`$c = new Celery('localhost', 'harvester', 'test', 'harvester', 'celery.harvester', 'celery.harvester');`
 `$result = $c->PostTask('tasks.add', array(2,2));`

**Comment by gjedeer** [comment]
If you can log in using the amqp library, maybe just compare the connection parameters which work for you with https://github.com/gjedeer/celery-php/blob/master/amqplibconnector.php#L71

![image](https://cloud.githubusercontent.com/assets/315648/14353100/edb4835a-fcd7-11e5-836c-383b202537ea.png)
