### ISSUE TITLE
Composer warning on install: "Package videlalvaro/php-amqplib is abandoned, you should avoid using it. Use php-amqplib/php-amqplib instead."

### ISSUE THREAD

**Issue by frankfarmer** [gjedeer/celery-php#74]
Composer is warning that `Package videlalvaro/php-amqplib is abandoned` when installing celery-php

```
$ tools/cli/composer.phar require massivescale/celery-php
Using version ^2.1 for massivescale/celery-php
./composer.json has been updated
  - Installing videlalvaro/php-amqplib (v2.6.3)
    Downloading: 100%

  - Installing massivescale/celery-php (2.1.1)
    Downloading: 100%

Package videlalvaro/php-amqplib is abandoned, you should avoid using it. Use php-amqplib/php-amqplib instead.
```

Is it feasible to replace this dependency?

**Comment by gjedeer** [comment]
Could you test if everything works with the recommended replacement package? It looks like just a rename.

On July 12, 2016 8:40:50 PM CEST, Frank Farmer <notifications@github.com> wrote:
>```
>$ tools/cli/composer.phar require massivescale/celery-php
>Using version ^2.1 for massivescale/celery-php
>./composer.json has been updated
>  - Installing videlalvaro/php-amqplib (v2.6.3)
>    Downloading: 100%
>
>  - Installing massivescale/celery-php (2.1.1)
>    Downloading: 100%
>
>Package videlalvaro/php-amqplib is abandoned, you should avoid using
>it. Use php-amqplib/php-amqplib instead.
>```
>
>`Package videlalvaro/php-amqplib is abandoned`
>Is it feasible to replace this dependency?
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/gjedeer/celery-php/issues/74

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by joehobson** [comment]
+1 for this issue. I was going to update my main project to use php-amqplib/php-amqplib but since celery-php stilll wants the videlalvaro version, gets complicated

**Comment by gjedeer** [comment]
If you want to speed it up, fork the project, see if the tests run correctly with the suggested replacement php-amqplib, send a pull request if the tests pass

**Comment by gjedeer** [comment]
That is fixed in celery4 branch of the project.
