### ISSUE TITLE
How can i get var_dump

### ISSUE THREAD

**Issue by anhnvname** [gjedeer/celery-php#75]
Hello,

How can i dump result from worker ?

My worker in python
#demo.py

`from celery import Celery
celery = Celery('tasks', broker='amqp://guest:guest@localhost:5672//')
celery.conf.update(
    CELERY_RESULT_SERIALIZER='json',
    CELERY_TASK_SERIALIZER='json',
    CELERY_TASK_RESULT_EXPIRES=None,
    CELERY_TRACK_STARTED = False,
)
@celery.task(queue='demo', name='add')
def add(x, y):
    return x + y`

My php script
`require 'celery-php/celery.php';
$c = new Celery('localhost', 'guest', 'guest', '/');
$result = $c->PostTask('tasks.add', array(2,2));`

but when i use var_dump($result); i can't dump result from woker.
In terminal show
`Received task: tasks.add[php_52b1759141a8b3.43107845]
Task tasks.add[php_52b1759141a8b3.43107845] succeeded in 0.000701383920386s: 4`

Show what i wrong some thing ?

Thanks so much !

**Comment by gjedeer** [comment]
Hi,

If you want to print some internal variable from AsyncResult object, just print it directly (echo $result->variable)

More likely, what you want to print is value returned from AsyncResult::get()

On July 18, 2016 6:20:07 AM CEST, anhnvname <notifications@github.com> wrote:
>Hello,
>
>How can i dump result from worker ?
>
>My worker in python
>#demo.py
>`from celery import Celery
>celery = Celery('tasks', broker='amqp://guest:guest@localhost:5672//')
>@celery.task(queue='demo', name='add')
>def add(x, y):
>    return x + y`
>
>My php script
>`require 'celery-php/celery.php';
>$c = new Celery('localhost', 'guest', 'guest', '/');
>$result = $c->PostTask('tasks.add', array(2,2));`
>
>but when i use var_dump($result); i can't dump result from woker.
>In terminal show
>`Received task: tasks.add[php_52b1759141a8b3.43107845]
>Task tasks.add[php_52b1759141a8b3.43107845] succeeded in
>0.000701383920386s: 4`
>
>Show what i wrong some thing ?
>
>Thanks so much !
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/gjedeer/celery-php/issues/75

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by anhnvname** [comment]
Hello,

Can u write some example ?
I try many ways but can't show anything.

**Comment by gjedeer** [comment]
Just see readme.md please. Or the unittest directory. Both have examples.

On July 18, 2016 11:43:42 AM CEST, anhnvname <notifications@github.com> wrote:
>Hello,
>
>Can u write some example ?
>I try many ways but can't show anything.
>
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/gjedeer/celery-php/issues/75#issuecomment-233286393

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by anhnvname** [comment]
Hello,

Before i made question, i'm tried many way, so. please help me

I want use php to show result from worker celery

All way from readme.md and test folder not working. it's show nothing

**Comment by gjedeer** [comment]
Ddi you try using an alphanumeric vhost name instead of "/"? If you don't know Celery too well, try following the examples more closely - use the connection details from examples, then move to your own values when examples work OK.

On July 18, 2016 12:20:41 PM CEST, anhnvname <notifications@github.com> wrote:
>Hello,
>
>Before i made question, i'm tried many way, so. please help me
>
>I want use php to show result from worker celery
>
>All way from readme.md and test folder not working. it's show nothing 
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/gjedeer/celery-php/issues/75#issuecomment-233293288

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by anhnvname** [comment]
Thanks for reply
I post my worker script and php script above, could u help me check it ?
Very close with example

**Comment by gjedeer** [comment]
So it doesn't work with an alphanumeric vhost name?

On July 18, 2016 12:43:58 PM CEST, anhnvname <notifications@github.com> wrote:
>Thanks for reply
>I post my worker script and php script above, could u help me check it
>?
>Very close with example
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/gjedeer/celery-php/issues/75#issuecomment-233297244

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by anhnvname** [comment]
Yes, it's not working with alphanumeric vhost name

**Comment by anhnvname** [comment]
Hello,

I'm tried using redis, and var_dump return body = null.

I'm tried use python to get result, it's OK

**Comment by anhnvname** [comment]
Hello,

i just remind, i want get result after post array to worker

php-celery do PostTask very well

**Comment by anhnvname** [comment]
Thanks for support, It's worked !

**Comment by anhnvname** [comment]
Hello,

How can i get original result ?, not json_decode ?

**Comment by gjedeer** [comment]
Call getCompleteResult()

On July 19, 2016 6:04:13 AM CEST, anhnvname <notifications@github.com> wrote:
>Hello,
>
>How can i get original result ?, not json_decode ?
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/gjedeer/celery-php/issues/75#issuecomment-233524736

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by anhnvname** [comment]
Thanks again, Everything work correctly !
